/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DownloadIndexRouteImport } from './routes/download/index'
import { Route as PolicyServiceIndexRouteImport } from './routes/policy/service/index'
import { Route as PolicyPrivacyIndexRouteImport } from './routes/policy/privacy/index'
import { Route as InviteCodeIndexRouteImport } from './routes/invite/$code/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadIndexRoute = DownloadIndexRouteImport.update({
  id: '/download/',
  path: '/download/',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyServiceIndexRoute = PolicyServiceIndexRouteImport.update({
  id: '/policy/service/',
  path: '/policy/service/',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyPrivacyIndexRoute = PolicyPrivacyIndexRouteImport.update({
  id: '/policy/privacy/',
  path: '/policy/privacy/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteCodeIndexRoute = InviteCodeIndexRouteImport.update({
  id: '/invite/$code/',
  path: '/invite/$code/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/download': typeof DownloadIndexRoute
  '/invite/$code': typeof InviteCodeIndexRoute
  '/policy/privacy': typeof PolicyPrivacyIndexRoute
  '/policy/service': typeof PolicyServiceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/download': typeof DownloadIndexRoute
  '/invite/$code': typeof InviteCodeIndexRoute
  '/policy/privacy': typeof PolicyPrivacyIndexRoute
  '/policy/service': typeof PolicyServiceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/download/': typeof DownloadIndexRoute
  '/invite/$code/': typeof InviteCodeIndexRoute
  '/policy/privacy/': typeof PolicyPrivacyIndexRoute
  '/policy/service/': typeof PolicyServiceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/download'
    | '/invite/$code'
    | '/policy/privacy'
    | '/policy/service'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/download'
    | '/invite/$code'
    | '/policy/privacy'
    | '/policy/service'
  id:
    | '__root__'
    | '/'
    | '/download/'
    | '/invite/$code/'
    | '/policy/privacy/'
    | '/policy/service/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DownloadIndexRoute: typeof DownloadIndexRoute
  InviteCodeIndexRoute: typeof InviteCodeIndexRoute
  PolicyPrivacyIndexRoute: typeof PolicyPrivacyIndexRoute
  PolicyServiceIndexRoute: typeof PolicyServiceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/': {
      id: '/download/'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy/service/': {
      id: '/policy/service/'
      path: '/policy/service'
      fullPath: '/policy/service'
      preLoaderRoute: typeof PolicyServiceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy/privacy/': {
      id: '/policy/privacy/'
      path: '/policy/privacy'
      fullPath: '/policy/privacy'
      preLoaderRoute: typeof PolicyPrivacyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$code/': {
      id: '/invite/$code/'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof InviteCodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DownloadIndexRoute: DownloadIndexRoute,
  InviteCodeIndexRoute: InviteCodeIndexRoute,
  PolicyPrivacyIndexRoute: PolicyPrivacyIndexRoute,
  PolicyServiceIndexRoute: PolicyServiceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
